export const categoriesAnUnits = {
  volume: {
    label: "Volume",
    standard: "liter",
    defaultInput: "us_gallon",
    defaultOutput: "liter",
    units: {
      liter: { label: "Liter", toStandard: 1 },
      milliliter: { label: "Milliliter", toStandard: 0.001 },
      cubic_meter: { label: "Cubic meter", toStandard: 1000 },
      cubic_foot: { label: "Cubic foot", toStandard: 28.3168 },
      cubic_inch: { label: "Cubic foot", toStandard: 0.0163871 },
      fluid_ounce: { label: "Fluid ounce", toStandard: 0.0295735 },
      us_gallon: { label: "US Gallon", toStandard: 3.78541 },
      us_quart: { label: "US quart", toStandard: 0.946353 },
      us_pint: { label: "US pint", toStandard: 0.473176 },
      us_cup: { label: "US legal cup", toStandard: 0.24 },
      imp_gallon: { label: "Imperial Gallon", toStandard: 4.54609 },
      imp_quart: { label: "Imperial quart", toStandard: 1.13652 },
      imp_pint: { label: "Imperial pint", toStandard: 0.568261 },
      imp_cup: { label: "Imperial cup", toStandard: 0.284131 },
    },
  },
  area: {
    label: "Area",
    standard: "sq_meter",
    defaultInput: "hectare",
    defaultOutput: "sq_meter",
    units: {
      sq_meter: { label: "Square meter", toStandard: 1 },
      sq_kilometer: { label: "Square Kilometer", toStandard: 1e6 },
      sq_mile: { label: "Square mile", toStandard: 2.59e6 },
      sq_yard: { label: "Square yard", toStandard: 0.836127 },
      sq_foot: { label: "Square foot", toStandard: 0.092903 },
      sq_inch: { label: "Square Inch", toStandard: 0.00064516 },
      hectare: { label: "Hectare", toStandard: 10000 },
      acre: { label: "Acre", toStandard: 4046.86 },
    },
  },
  mass: {
    label: "Mass",
    standard: "kilogram",
    defaultInput: "pound",
    defaultOutput: "kilogram",
    units: {
      kilogram: { label: "Kilogram", toStandard: 1 },
      gram: { label: "Gram", toStandard: 0.001 },
      milligram: { label: "Milligram", toStandard: 1e-6 },
      tonne: { label: "Tonne", toStandard: 1000 },
      imp_ton: { label: "Imperial ton", toStandard: 1016.05 },
      us_ton: { label: "US ton", toStandard: 907.185 },
      stone: { label: "Stone", toStandard: 6.35029 },
      pound: { label: "Pound", toStandard: 0.453592 },
      ounce: { label: "Ounce", toStandard: 0.0283495 },
    },
  },
  length: {
    label: "Length",
    standard: "meter",
    defaultInput: "inch",
    defaultOutput: "meter",
    units: {
      meter: { label: "Meter", toStandard: 1 },
      kilometer: { label: "Kilometer", toStandard: 1000 },
      centimeter: { label: "Centimeter", toStandard: 1e-2 },
      millimetre: { label: "Millimetre", toStandard: 1e-3 },
      micrometre: { label: "Micrometre", toStandard: 1e-6 },
      nanometre: { label: "Nanometre", toStandard: 1e-9 },
      mile: { label: "Mile", toStandard: 1609.34 },
      yard: { label: "Yard", toStandard: 0.9144 },
      foot: { label: "Foot", toStandard: 0.3048 },
      inch: { label: "Inch", toStandard: 0.0254 },
    },
  },
  speed: {
    label: "Speed",
    standard: "kmph",
    defaultInput: "mps",
    defaultOutput: "kmph",
    units: {
      mps: { label: "Meter per second", toStandard: 3.6 },
      kmph: { label: "Kilometer per hour", toStandard: 1 },
      mileph: { label: "Mile per hour", toStandard: 1.60934 },
      fps: { label: "Foot per second", toStandard: 1.09728 },
      knot: { label: "Knot", toStandard: 1.852 },
    },
  },
  time: {
    label: "Time",
    standard: "second",
    defaultInput: "hour",
    defaultOutput: "second",
    units: {
      millisecond: { label: "Millisecond", toStandard: 0.001 },
      second: { label: "Second", toStandard: 1 },
      minute: { label: "Minute", toStandard: 60 },
      hour: { label: "Hour", toStandard: 3600 },
      day: { label: "Day", toStandard: 86400 },
      week: { label: "Week", toStandard: 604800 },
      month: { label: "Month", toStandard: 2.628e6 },
      year: { label: "Calendar year", toStandard: 3.154e7 },
      decade: { label: "Decade", toStandard: 3.154e8 },
      century: { label: "Century", toStandard: 3.154e9 },
    },
  },
  energy: {
    label: "Energy",
    standard: "joule",
    defaultInput: "joule",
    defaultOutput: "kilocalorie",
    units: {
      joule: { label: "Joule", toStandard: 1 },
      kilojoule: { label: "KiloJoule", toStandard: 1000 },
      gramcalorie: { label: "Gram Calorie", toStandard: 4.184 },
      kilocalorie: { label: "KiloCalorie", toStandard: 4184 },
      watthour: { label: "Watt hour", toStandard: 3600 },
      kilowatthour: { label: "Kilowatt hour", toStandard: 3.6e6 },
      electronvolt: { label: "Electronvolt", toStandard: 1.6022e-19 },
    },
  },
  frequency: {
    label: "Frequency",
    standard: "hertz",
    defaultInput: "hertz",
    defaultOutput: "kilohertz",
    units: {
      hertz: { label: "Hertz", toStandard: 1 },
      kilohertz: { label: "Kilohertz", toStandard: 1000 },
      megahertz: { label: "Megahertz", toStandard: 1e6 },
      gigahertz: { label: "Gigahertz", toStandard: 1e9 },
    },
  },
  pressure: {
    label: "Pressure",
    standard: "bar",
    defaultInput: "pascal",
    defaultOutput: "bar",
    units: {
      bar: { label: "Bar", toStandard: 1 },
      pascal: { label: "Pascal", toStandard: 1e-5 },
      st_atm: { label: "Standard Atmosphere", toStandard: 1.01325 },
      torr: { label: "Torr", toStandard: 0.00133322 },
    },
  },
  storage: {
    label: "Digital Storage",
    standard: "byte",
    defaultInput: "kilobyte",
    defaultOutput: "byte",
    units: {
      byte: { label: "Byte", toStandard: 1 },
      kilobyte: { label: "Kilobyte", toStandard: 1000 },
      kibibyte: { label: "Kibibyte", toStandard: 1024 },
      megabyte: { label: "Megabyte", toStandard: 1e6 },
      mebibyte: { label: "Mebibyte", toStandard: 1.049e6 },
      gigabyte: { label: "Gigabyte", toStandard: 1e9 },
      gibibyte: { label: "Gibibyte", toStandard: 1.074e9 },
      terabyte: { label: "Terabyte", toStandard: 1e12 },
      tibibyte: { label: "Tibibyte", toStandard: 1.1e12 },
      petabyte: { label: "Petabyte", toStandard: 1e15 },
      pebibyte: { label: "Pebibyte", toStandard: 1.126e15 },
      bit: { label: "Bit", toStandard: 0.125 },
      kilobit: { label: "Kilobit", toStandard: 125 },
      kibibit: { label: "Kibibit", toStandard: 128 },
      megabit: { label: "Megabit", toStandard: 125000 },
      mebibit: { label: "Mebibit", toStandard: 131072 },
      gigabit: { label: "Gigabit", toStandard: 1.25e8 },
      gibibit: { label: "Gibibit", toStandard: 1.342e8 },
      terabit: { label: "Terabit", toStandard: 1.25e11 },
      tibibit: { label: "Tibibit", toStandard: 1.374e11 },
      petabit: { label: "Petabit", toStandard: 1.25e14 },
      pebibit: { label: "Pebibit", toStandard: 1.407e14 },
    },
  },
  angle: {
    label: "Plane Angle",
    standard: "degree",
    defaultInput: "degree",
    defaultOutput: "radian",
    units: {
      degree: { label: "Degree", toStandard: 1 },
      radian: { label: "Radian", toStandard: 57.2958 },
      milliradian: { label: "Milliradian", toStandard: 0.0572958 },
      gradian: { label: "Gradian", toStandard: 0.9 },
      minute_arc: { label: "Minute of arc", toStandard: 1 / 60 },
      second_arc: { label: "Second of arc", toStandard: 1 / 3600 },
    },
  },
  //temperature conversion is special (no simple multiplication)
  temperature: {
    label: "Temperature",
    defaultInput: "fahrenheit",
    defaultOutput: "celsius",
    units: {
      celsius: {
        label: "Celsius",
        to: {
          celsius: "x",
          kelvin: "x+273.15",
          fahrenheit: "(x*9/5)+32",
        },
      },
      fahrenheit: {
        label: "Fahrenheit",
        to: {
          celsius: "(x-32)*5/9",
          kelvin: "(x-32)*5/9+273.15",
          fahrenheit: "x",
        },
      },
      kelvin: {
        label: "Kelvin",
        to: {
          celsius: "x-273.15",
          kelvin: "x",
          fahrenheit: "((x-273.15)*9/5)+32",
        },
      },
    },
  },
};

//   temperature: {},
